name: Build

on:
  workflow_call:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Installing"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Building"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing"
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Pushing"