name: Build

on:
  workflow_call:

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build \
          -t test-image \
          .
      - name: Docker save
        run: |
          docker save test-image > /tmp/image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar
  push:
    name: Push
    needs: image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [env1, env2, env3]
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp
      - name: Docker load
        run: |
          docker load --input /tmp/image.tar
      - name: Docker image ls
        run: |
          docker image ls -a
