name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t image:${{ github.sha }} .
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "image:${{ github.sha }}"