name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build \
          -t test-image \
          --output type=docker,dest=/tmp/image.tar \
          .
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar
  push:
    name: Push
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [region-1, region-2, region-3]
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp
      - name: Docker load
        run: |
          docker load --input /tmp/image.tar
      - name: Docker image ls
        run: |
          docker image ls -a
