name: Build

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      regions:
        required: true
        type: string
      tag:
        required: false
        default: ${{ inputs.sha }}
        type: string

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          sha: ${{ inputs.sha }}
      - name: Docker build
        run: |
          docker build \
          -t test-image \
          .
      - name: Docker save
        run: |
          docker save test-image > /tmp/image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar
  prep-matrix:
    name: Prepare matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix=$(echo '${{ inputs.regions }}' | sed -r 's/ /\n/g' | jq -Rsc 'split("\n")[:-1]')
          echo $matrix
          echo "::set-output name=matrix::$(echo $matrix)"
  push:
    name: Push
    needs: [image, prep-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJSON(needs.prep-matrix.outputs.matrix) }}
    environment: ${{ matrix.region }}
    steps:
      - uses: actions/checkout@v2
        with:
          sha: ${{ inputs.sha }}
      - run: |
          yarn install
      - id: resolve-region
        uses: ./.github/actions/resolve-region
        with:
          region: ${{ matrix.region }}
      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp
      - name: Docker load
        run: |
          docker load --input /tmp/image.tar
      - name: Docker image ls
        run: |
          docker image ls -a
      - name: Tag image
        run: |
          echo 'Tagging image with ${{ inputs.tag }} at ${{ steps.resolve-region.outputs.region }}'