name: Build

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t image:${{ inputs.sha }} .
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "image:${{ inputs.sha }}"