name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      uuid:
        required: true
        type: string

jobs:
  deployment:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      - name: deploy
        run: |
          echo "UUID: ${{ inputs.uuid }}"