name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/deployment.yml

jobs:
  staging:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - name: deploy
        run: |
          echo "hello world"
  production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: deploy
        run: |
          echo "hello world"

