name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  env1:
    environment: env1
    needs: build
    uses: ./.github/workflows/release.yml
      with:
        region: region-1
  # env2:
  #   environment: env2
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: ./.github/workflows/release.yml
  #       with:
  #         region: region-2
  # env3:
  #   environment: env3
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: ./.github/workflows/release.yml
  #       with:
  #         region: region-3
  # env4:
  #   environment: env4
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: ./.github/workflows/release.yml
  #       with:
  #         region: region-4
  # env5:
  #   environment: env5
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: ./.github/workflows/release.yml
  #       with:
  #         region: region-5
