name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      sha: ${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [env1, env2, env3, env4, env5]
    steps:
      - name: push
        run: |
          echo "Pushing image to ${{ inputs.environment }} with ${{ inputs.sha }} "
      - name: tag
        run: |
          echo "Taging image ${{ inputs.environment }} with ${{ inputs.sha }} "