name: Main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/build.yml
    with:
      regions: env1 env2
      sha: ${{ github.sha }}
      tag: ${{ github.sha }}