name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      sha: ${{ github.sha }}
  deploy:
    strategy:
      matrix:
        environment: [env1, env2, env3, env4, env5]
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      environment: ${{ matrix.environment }}
      sha: ${{ github.sha }}
