on:
  workflow_call:
    inputs:
      environments:
        required: true
        type: string
    outputs:
      matrix:
        description: Matrix as a JSON string
        value: ${{ jobs.prep-matrix.outputs.matrix }}

jobs:
  prep-matrix:
    name: Prepare matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix=$(echo '${{ inputs.environments }}' | sed -r 's/ /\n/g' | jq -Rsc 'split("\n")[:-1]')
          echo ::set-output name=matrix::$(echo $matrix)\"