name: Pull Request

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy
    uses: ./.github/workflows/staging.yml
    with:
      environment: staging
      uuid: ${{ needs.build.outputs.uuid }}