name: Pull Request

on:
  pull_request:
    types:
      - ready_for_review
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/build.yml
    with:
      regions: env1
      sha: ${{ github.sha }}
      tag: "pr-${{ github.event.number }}"
