name: Pull Request

on:
  pull_request:
    branches:
      main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      regions: env1
      sha: ${{ github.sha }}
      tag: "pr-${{ github.event.number }}"
