name: Release

on:
  workflow_call:
    inputs:
      region: 
        required: true
        type: string
      environment:
        required: false
        type: string

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Tag image
        run: |
          echo "Taging image"