name: Release

on:
  workflow_call:
    inputs:
      region: 
        required: true
        type: string

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "image:${{ github.sha }}"
      - name: Push image
        run: |
          echo "Pushing image"
      - name: Tag image
        run: |
          echo "Taging image"