name: Release

on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Deploying to ${{ inputs.environment }} with ${{ inputs.sha }} "