name: Release

on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Pushing image to ${{ inputs.environment }} with ${{ inputs.sha }} "
  deploy:
    name: Deploy
    needs: push
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Deploying to ${{ inputs.environment }} with ${{ inputs.sha }} "