name: Release

on:
  workflow_call:
    inputs:
      region: 
        required: true
        type: string
      artifact_name: 
        required: true
        type: string

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: ${{ inputs.artifact_name }}
      - name: Push image
        run: |
          echo "Pushing ${{ inputs.artifact_name }}"
      - name: Tag image
        run: |
          echo "Taging ${{ inputs.artifact_name }}"