name: Release

on:
  workflow_call:

jobs:
  tag:
    name: Tag image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [env1, env2, env3]
    environment: ${{ matrix.region }}
    steps:
      - name: Tag image
        run: |
          echo "Taging image"