name: Release

on:
  workflow_call:
    inputs:
      region: 
        required: true
        type: string

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - run: |
          echo "Pushing image to ${{ inputs.region }} with ${{ github.sha }} "
  tag:
    name: Tag Image with production
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - run: |
          echo "Taging image ${{ inputs.region }} with ${{ github.sha }} "